version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

hooks:
  BeforeInstall:
    - location: beforeinstall.sh
      runas: root
  AfterInstall:
    - location: npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: npm-start.sh
      runas: root
      timeout: 60
    
    


