version: 0.0
os: linux
files:
  - source: resumeTrial-master/views/index.html
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: npm-install.sh
      runas: root
  AfterInstall:
    - location: npm-start.sh
      runas: root
      timeout: 300
 # ApplicationStart:
   # - location: npm-start.sh
     # runas: root
     # timeout: 60
    
    


