version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

hooks:
  BeforeInstall:
    - location: test3/resumeTrial-master/scripts/beforeinstall.sh
      runas: root
  AfterInstall:
    - location: test3/resumeTrial-master/scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: test3/resumeTrial-master/scripts/npm-start.sh
      runas: root
      timeout: 60
    
    
